<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Styles [
        <!ELEMENT Styles (Style)*>
        <!ELEMENT Style (Format)*>
        <!ATTLIST Style
                FontChange CDATA #IMPLIED
                ID CDATA #REQUIRED
                Name CDATA #REQUIRED
                Next CDATA #IMPLIED
                Shortcut CDATA #IMPLIED
                Type CDATA #REQUIRED>
        <!ELEMENT Format (#PCDATA)>
        ]>
<Styles>
    <Style Name="Title" ID="652D030B-03CB-41AE-9E3A-7A54C44645EB" Type="Para+Char" FontChange="Size">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Palatino-Roman;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\sl264\slmult1\sb260\pardirnatural\partightenfactor0

\f0\fs56 \cf0 <$ScrKeepWithNext>Attributes}]]></Format>
    </Style>
    <Style Name="Heading 1" ID="A29B3E1A-40E0-471E-B9B9-8C4ED7E036A0" Type="Para+Char" FontChange="Size" Shortcut="4">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\froman\fcharset0 Palatino-Bold;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\sl264\slmult1\sb260\pardirnatural\partightenfactor0

\f0\fs24 \cf0 <$ScrKeepWithNext><$Scr_H::1>
\f1\b\fs36 Attributes
\f0\b0\fs24 <!$Scr_H::1>}]]></Format>
    </Style>
    <Style Name="Heading 2" ID="1226C1DB-6280-40B3-8BEB-AB9C228FC9D7" Type="Para+Char" FontChange="Size" Shortcut="5">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\froman\fcharset0 Palatino-Bold;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\sl264\slmult1\sb260\pardirnatural\partightenfactor0

\f0\fs24 \cf0 <$ScrKeepWithNext><$Scr_H::2>
\f1\b\fs26 Attributes
\f0\b0\fs24 <!$Scr_H::2>}]]></Format>
    </Style>
    <Style Name="Centered Text" ID="D0DD1176-13FF-433A-8195-9BEEAE6286E0" Type="Para" Shortcut="1">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Palatino-Roman;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx360\tx720\tx1080\tx1440\tx1800\tx2160\tx2880\tx3600\tx4320\sl264\slmult1\pardirnatural\qc\partightenfactor0

\f0\fs26 \cf0 Attributes}]]></Format>
    </Style>
    <Style Name="Block Quote" ID="CEFBBBCC-6DFF-4A62-9BC3-1698FF145168" Type="Para" FontChange="Size" Shortcut="2">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Palatino-Roman;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx720\tx1080\tx1440\li720\sl264\slmult1\sb240\sa240\pardirnatural\partightenfactor0

\f0\fs24 \cf0 Attributes}]]></Format>
    </Style>
    <Style Name="Attribution" ID="6EBE0ECB-F18D-4ED9-95F8-EA1A09D7376E" Type="Para" FontChange="Size" Shortcut="">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Palatino-Roman;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx720\tx1080\tx1440\li720\sl264\slmult1\sa240\pardirnatural\qr\partightenfactor0

\f0\fs24 \cf0 Attributes}]]></Format>
    </Style>
    <Style Name="Code Block" ID="F363FCB8-7116-48AE-A1BF-33D2262CD671" Type="Para+Char" FontChange="Face+Size" Next="F363FCB8-7116-48AE-A1BF-33D2262CD671">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx720\tx1080\tx1440\tx1800\tx2160\li720\pardirnatural\partightenfactor0

\f0\fs22 \cf0 Attributes}]]></Format>
    </Style>
    <Style Name="Verse" ID="80BBBC58-541E-4CB3-B622-7C538B4D36AB" Type="Para" FontChange="Size" Next="80BBBC58-541E-4CB3-B622-7C538B4D36AB">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Palatino-Roman;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\sl264\slmult1\pardirnatural\qc\partightenfactor0

\f0\fs24 \cf0 Attributes}]]></Format>
    </Style>
    <Style Name="Code Span" ID="15AED48D-6EB1-428E-8434-EB6CB2A6D3A8" Type="Char" FontChange="Face+Size">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx720\tx1080\tx1440\tx1800\tx2160\li720\pardirnatural\partightenfactor0

\f0\fs22 \cf0 Attributes}]]></Format>
    </Style>
    <Style Name="Caption" ID="0CF0E836-268C-4672-A978-31E9414BC2BC" Type="Para" FontChange="Size" Shortcut="3">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Palatino-Roman;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\sl264\slmult1\sa160\pardirnatural\qc\partightenfactor0

\f0\fs26 \cf0 Attributes}]]></Format>
    </Style>
    <Style Name="Emphasis" ID="DF8D61C6-4A89-4274-8A7A-4018F1F07D76" Type="Char">
        <Format><![CDATA[{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Palatino-Italic;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\pard\tx360\tx720\tx1080\tx1440\tx1800\tx2160\tx2880\tx3600\tx4320\fi360\sl264\slmult1\pardirnatural\partightenfactor0

\f0\i\fs26 \cf0 Attributes}]]></Format>
    </Style>
</Styles>
